PRODUCT_LABELS = {
    'Combo 4 Vị Bơ Điều "Thần Thánh" - Quết Bánh Mì Đỉnh Nóc, Ăn Vã Không Sợ Mập! Dập Tắt Hoàn Toàn Định Kiến Đồ Ăn Kiêng!': 'SKU35: Bơ Điều Thần Thánh',
    'COMBO 3 vị gói lớn BẮP NƯỚNG CHAY KIỂU NHẬT - KHÔNG DẦU MỠ! Trọn Bộ 3 Vị Độc Bản, Bùng nổ vị giắc từ Ngọt Đến Mặn Không Sợ Béo ! Nhai Rào Rạo Điếc Tai': 'SKU38: Bắp Nướng Nhật',
    'Combo 5 Vị Khoai Môn Sợi Mặn Ngọt Đảo Điên - Bụng Đói Được Nuông Chiều Tới Bến! Mua 1 Lần Nhai Mỏi Miệng Cả Tháng!': 'SKU36: Khoai Môn Sợi',
    'Combo 3 Vị Khoai Tím Đỉnh Nóc - Ngọt Mật Thơm Bắp, Càng Nhai Càng Cuốn! - Cắn Vỡ Vụn, Ngọt Lịm Tim! Nhấp Chốt Ngay Kẻo Bốc Hơi Trong 1 Phút!': 'SKU33: Khoai Tím',
    'COMBO 3 Chuối Sấy Mix Hạt Granola Nguyên Bản Áo Hạt - Ngọt Mật Tự Nhiên Cuốn Cứng Ngắc! Ăn Sập Tủ Mà Vẫn Nhẹ Tênh Vóc Dáng! ️đồ ăn vặt': 'SKU30: Chuối Sấy',
    'Siêu Combo Rong biển kẹp hạt 3 vị - Truyền thống / phô mai / chà bông đồ ăn vặt': 'SKU28: Rong Biển Kẹp Hạt',
    'Combo 8 Bánh Tráng Nướng Côba Mix Vị Khô Mực Nướng,Tôm Cay, Mắm Tỏi , Gà Cay Lạ Miệng': 'SKU12: Bánh Tráng Cô Ba',
    'Combo 3 Túi Chuối Xanh Sấy Giòn Đủ Vị - Đẫm Sốt Mắm Hành & Hải Sản, Thơm Bùi Mật Ong Cuốn Lưỡi! Tẩm Ướp Đậm Đà, Nhai Vui Miệng Cực Cuốn!': 'SKU... Chuối Xanh Sấy',
    'SIÊU COMBO GIA HƯNG - Khoai Tây Lắc Siêu Nhiều Phô Mai - 400g đồ ăn vặt': 'SKU4: Khoai Lắc',
    'Bắp Chiên cháy tỏi ớt Gói 500g - (Sản phẩm đổi tên thành Bắp chiên cháy tỏi) đồ ăn vặt': 'SKU23: Bắp Chiên',
    'Combo 3 Hộp Viên Dừa Nướng Cuộn Sợi - Giòn Rụm, Thơm Lừng! Làm Từ Dừa Tươi Nguyên bản': 'SKU39: Viên Dừa Nướng',
    'Combo Bánh Tráng Sấy Mix Bò Tỏi & Mắm Tép NHIỀU - Đậm Đà Cay Tê, Nhai Quên Lối Về! ️Ngon Vô Tri Đánh Gục Mọi Chiếc Bụng Đói! đồ ăn vặt': 'SKU34: Bánh Tráng Tép',
    'Siêu Combo 10 Túi Đậu Phộng Sanchi Nhiều Vị Giòn Tan Trong Miệng - Snack Ăn Vặt đồ ăn vặt': 'SKU21: Sanchi',
    'Combo Khoai Môn 3 Vị Chấn Động! Nhai Ồn Ào Đánh Thức Cả Xóm Chốt Đơn! - Ngọt, Mặn, Cay Tê Đỉnh Chóp! ️ anvat vietnam snack mix vi đồ ăn vặt': 'SKU32: Khoai Môn',
    'Combo 20 Mix 2 Vị Bánh Cuộn KAMAN Lava - Vỏ Giòn Khấu, Lõi Chảy Béo Ngậy! Cắn 1 Phát Nhân Trào Đỉnh Nóc! Lốc KAMAN Nhân Chảy - Nữ Hoàng Bánh Nướng Trà Chiều! đồ ăn vặt': 'SKU11: KAMAN',
    'Combo Hộp Quà Bánh trung thu "Tết Đoàn Viên" 6 Vị Độc Bản! Gói Trọn Tinh Hoa - Tôn Vinh Người Nhận ! Cắt 1 Miếng Trào Dâng Vị Giác, Ăn Là Dính!': 'SKU... Trung Thu Tết Đoàn Viên',
    'Combo Bất Bại: Cặp Đôi Bánh Quy Hành Kẹp Phô Mai & Trứng Muối (250gr)..Bánh Quy Hành Kẹp Kéo Sợi - Vỏ Giòn Rụm Nghe Đã Tai, Nhân Dẻo Quánh Béo Ngậy đồ ăn vặt': 'SKU6: Bánh Quy Hành Kẹp',
    'Nui Chiên Giòn Mắm Tỏi - 500gr và 300gr An vặt ngon, snack ngon, snack rẻ snack tổng hợp đồ ăn vặt snack hình nui cong': 'SKU20: Nui',
    'Combo Tam Sắc Bánh Dừa Nướng - Nhai Giòn Rụm, Cuốn Tới Cùng! 3 Vị Bánh Dừa Nướng Đỉnh Cao Xứ Quảng... đồ ăn vặt': 'SKU7: Bánh Dừa Nướng',
    'Mailey Thanh Gạo Lứt Dinh Dưỡng Vị Chà Bông / Rong Biển / Phô Mai / Hải sản - Gói 10 Thanh Bánh đồ ăn vặt': 'SKU3: Mailey Thanh Gạo Lứt (Mã 2)',
    'Siêu Combo YIDISI 4 Gói Bánh Nghìn lớp Giòn Hương Vị Phô Mai Và Sữa Béo Thơm Ngon gói 118g - Bánh Quy, Ắn Vặt , Bánh Xốp snack Bánh Kẹo Tết -Mua sắm Tết -DEAL TẾT 2026-Bao Lì Xì đồ ăn vặt': 'SKU... Yidisi Nghìn Lớp',
    'Siêu Combo An Việt - 1kg Cơm Sấy Gạo Lứt Chà Bông Đồ Ăn Vặt Healthy Dành Cho Người Ăn Kiêng Ít Cay': 'SKU22: Cơm Sấy',
    'Thanh Gạo Lứt Dinh Dưỡng Mix Vị Chà Bông / Rong Biển / Hải Sản / Phô Mai - Gói 10 Thanh đồ ăn vặt': 'SKU2: Thanh Gạo Lứt Mailey(Mã 1)',
    'Combo 3 Túi Nougat Cốt Sữa Mềm Dẻo - Ngập Ngụa Trái Cây Sấy ! Nougat Trái Cây "Cắt Đường" - Ăn Thả Ga Không Lo Bé Mỡ! an vat tuoi tho anvat vietnam snack tala đồ ăn vặt': 'SKU10: Kẹo Nougat',
    'COMBO Bánh Quy Dinh Dưỡng Tứ Sắc - Khai Hoa Tứ Sắc - Tròn Vị Bơ, Thơm Vị Hạt ! Bánh Quy Bơ Tạo Hình Hoa Mix Hạt Thượng Hạng 250gr Ăn Vặt anvat vietnam snack tala đồ ăn vặt': 'SKU8: Quy Tứ Sắc',
    'COMBO Xoài Mắm Ớt - Chua Cay Tê Tái - Xoài Dẻo Đẫm Sốt Mắm Kẹo - Nhìn Là Thèm, Cắn Là Sướng! đồ ăn vặt': 'SKU19: Xoài Sấy',
    'COMBO MÌ TRỘN LÚA NỔI: SỢI MÌ TỪ "CÂY LÚA BIẾT BƠI" - ĂN NGON KHÔNG LO NÓNG! Mì Trộn Hộp Giấy Lúa Nổi "Thuận Thiên": Tinh Hoa Ớt Mè Tía Tô x Sốt Vị Quảng - Trộn Là Dính - 3 Phút Có Ăn Ngay đồ ăn vặt': 'SKU16: Mì Lúa Nổi',
    'COMBO Nui Ăn Vặt "HOÀNG KIM" VỊ ĐỈNH CAO Giòn Thơm, Đậm Đà ! Nui Sấy Tẩm Vị - Đẫm Sốt Đỉnh Chóp, Nhai Rộp Rộp Điếc Tai ️️... 300gr đồ ăn vặt': 'SKU31: Nui 6 Vị',
    'GIA HƯNG - Combo 3 Snack Siêu Hot: Nui Chiên Giòn, Khoai Tây Phô Mai & Bắp Tỏi Ớt Chiên - Vị Ngọt Mặn Hài Hòa, Giòn Rụm, Thơm Béo, Đóng Zipper Kín đồ ăn vặt': 'SKU37: Combo 3 Snack Siêu Hot',
    'SIÊU Combo 5 Vị Khoai Lang & Khoai Môn Chiên Giòn - Đã Bóc Túi Là Không Thể Dừng - Set Khoai Lát Mỏng Đẫm Vị - Giòn Tan Nhức Nách! - "Kẻ Hủy Diệt" Mồi 250gr đồ ăn dacsannb snack tala đồ ăn vặt': 'SKU1: Khoai Lang & Khoai Môn',
    'Siêu Combo 27 gói Bánh Tráng 9 Vị MèoFood - Tỏi Ớt, Sa tế, Hải Sản, Rong Biển,... Cực Cuốn - Ăn Vặt , Bánh Tráng snack Bánh Kẹo đồ ăn vặt': 'SKU15: Bánh Tráng Mèo Food',
    'SIÊU COMBO GIA HƯNG - Bánh Tai Heo Nhí Hủ 350g Mix 2 hoặc 3 Vị Trong Hũ Đựng Đa Màu Sắc Bánh Kẹo Tết -Mua sắm Tết -DEAL TẾT 2026-Bao Lì Xì đồ ăn vặt': 'SKU29: Tai Heo Nhí',
    'Huenuts - Combo 4 Gói Hạt Nuts Mix Vị Đậu Phộng Tỏi Ớt Rong Biển & Hướng Dương Chiên Giòn Ăn Vặt Ăn Nhanh Bánh Kẹo Hương Vị Cay Nồng Hấp Dẫn Bánh Kẹo Tết -Mua sắm Tết -DEAL TẾT 2026-Bao Lì Xì đồ ăn vặt': 'SKU27: Hạt Nuts Mix',
    'Combo 3 Túi Thèo Lèo Đậm Vị - Giòn Rụm Ký Ức, Cuốn Hơn Xưa! Combo Quẩy Que Giòn Khấu - Ngoài Đẫm Vị Cay, Trong Giòn Tan Gãy! đồ ăn vặt việt nam dacsannb đồ ăn vặt': 'SKU26: Thèo Lèo',
    'COMBO Siêu phẩm Bánh Tuyết Trứng Muối vs Trái cây Cắt Lát Mềm Tan đồ ăn vặt': 'SKU5: Bông Lan Tuyết',
    'Bánh Snack Kelum SIÊU TO KHỔNG LỒ- Bánh Bắp 180g Và Bánh Phồng Tôm 120g đồ ăn vặt': 'SKU18: Kelum cũ',
    "Combo 6 Ly Bỏng Ngô Đôlar's Corner Vị Socola , Matcha, Phô Mai, Caramel Milk Ngọt Ngào Từng Hạt - Bắp Rang đồ ăn vặt": 'SKU13: Bắp Đô La',
    'Combo 3 Túi Tai Heo Mắm Ớt -Cay Tê Đầu Lưỡi, Nổ Tung Vị Giác! Bốc 1 Miếng Dính Cứng Ngắc -Lốc 3 Túi Tai Heo Sấy Giòn - Chua Cay Mặn Ngọt Đủ Hệ! 500gr đồ ăn vặt việt nam dacsannb an vat tuoi tho': 'SKU25: Tai Heo Mắm Ớt',
    'COMBO 3 Túi Bánh Dứa Nhỏ Xinh - Trong Dẻo Quánh, Ngoài Tan Nhanh! - Chua Ngọt Đỉnh Chóp! Vỏ Mềm Tan, Nhân Ngọt Thanh Không Ngấy... 250gr đồ ăn anvat vietnam snack tala thuc pham ban': 'SKU9: Bánh Dứa',
    'COMBO 2 BÁNH YIDISI - CẶP ĐÔI XUÂN - 2 vị Gói Bánh Nghìn lớp Giòn Hương Vị Phô Mai Và Sữa Béo Thơm Ngon gói 118g - Bánh Quy, Ắn Vặt , Bánh Xốp snack': 'SKU17: Yidisi',
    'SIÊU COMBO Bánh Snack Kelum SIÊU TO KHỔNG LỒ- Bánh Tôm Chiên Giòn 160g Và Bánh Lốc Xoáy 160g': 'SKU14: Kelum mới',
    'Combo 3 Vị Bánh Thuyền Mix Ngập Hạt Ngon Đỉnh Nóc Kịch Trần! - Siêu Phẩm Ăn Vặt Không Lo Béo: Bánh Thuyền Mix Hạt Tràn Viền Topping': 'SKU... Bánh Thuyền Mix Hạt',
    'SIÊU COMBO Gia Hưng - Hộp Gạo Lứt Rang Vị Rong Biển Giòn 320g Combo 3 Ăn Thả Ga Giòn Tan Từng Hạt Thơm Ngon Mê Li Không Chất Bảo Quản': 'SKU24: Hộp Gạo Lứt Rang',
    'COMBO Cool 6 Ly Trà Sữa, Trái Cây Trân Châu Tự Pha Thơm Ngon Hương Vị Tự Nhiên Chất Lượng Cao cho trải nghiệm tuyệt vời Bánh Kẹo': 'SKU... Trà Sữa Tự Pha',
    'HÀNG TẶNG KHÔNG BÁN ( GIỚI HẠN) - 1 THANH RONG BIỂN KẸP CHÀ BÔNG': '[Tặng] Thanh Rong Biển',
    '(HÀNG TẶNG KÈM COMBO KHÔNG BÁN) Ngẫu Nhiên Bánh Tráng 9 Vị MèoFood - Tỏi Ớt, Sa tế, Hải Sản, Rong Biển,... Cực Cuốn - Ăn Vặt , Bánh Tráng snack Bánh Kẹo Tết -Mua sắm Tết -DEAL TẾT 2026-Bao Lì Xì': '[Tặng] Bánh Tráng MèoFood',
    'Deal 9k Bánh Bông Lan Mix Vi - Độc Quyền Phiên Live': 'Bánh Bông Lan Deal 9k',
    '( CHỈ CÓ TRÊN LIVE ) DEAL quà tặng ưu đãi 1 THANH GẠO LỨT vị ngẫu nhiên dành cho khách đặt đơn trên LIVE sản phẩm đặc biệt chỉ áp dụng cho đơn hàng trên LIVE': '[Tặng Live] Thanh Gạo Lứt',
    'chamr quà tặng ngẫu nhiên kèm khi mua bánh': '[Tặng] Charm Ngẫu Nhiên',
    '(QUÀ TẶNG KHÔNG BÁN) Thanh Gạo Lứt, Bánh Kẹo, Thanh Năng Lượng, chamr đính túi giày dép': '[Tặng] Thanh NL / Charm'
}